# Generated by Django 4.2.7 on 2025-07-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etl_demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='etlsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
