# Generated by Django 4.2.7 on 2025-08-03 12:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('airflow_demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAGRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dag_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Em Fila'), ('RUNNING', 'Executando'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falha')], default='QUEUED', max_length=20)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('failed_tasks', models.IntegerField(default=0)),
                ('log_output', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DAG Run',
                'verbose_name_plural': 'DAG Runs',
            },
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Em Fila'), ('RUNNING', 'Executando'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falha')], default='QUEUED', max_length=20)),
                ('log_output', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('dag_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_instances', to='airflow_demo.dagrun')),
            ],
            options={
                'verbose_name': 'Task Instance',
                'verbose_name_plural': 'Task Instances',
            },
        ),
    ]
