# Generated by Django 4.2.7 on 2025-07-28 22:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nome da Tabela"
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(verbose_name="Última Atualização"),
                ),
                (
                    "record_count",
                    models.IntegerField(verbose_name="Número de Registros"),
                ),
                (
                    "date_range_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Início do Período"
                    ),
                ),
                (
                    "date_range_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fim do Período"
                    ),
                ),
                ("tickers", models.JSONField(default=list, verbose_name="Tickers")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Criação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metadado",
                "verbose_name_plural": "Metadados",
                "db_table": "data_metadata",
                "ordering": ["-last_update"],
            },
        ),
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="Data/Hora")),
                ("ticker", models.CharField(max_length=10, verbose_name="Ticker")),
                (
                    "open",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço de Abertura",
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Preço de Fechamento",
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço Máximo",
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço Mínimo",
                    ),
                ),
                (
                    "volume",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Volume"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dado de Ação",
                "verbose_name_plural": "Dados de Ações",
                "db_table": "stock_data",
                "ordering": ["-datetime", "ticker"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalIndicators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="Data/Hora")),
                ("ticker", models.CharField(max_length=10, verbose_name="Ticker")),
                (
                    "daily_return",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Retorno Diário",
                    ),
                ),
                (
                    "daily_log_return",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Retorno Log Diário",
                    ),
                ),
                (
                    "cumulative_return",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Retorno Acumulado",
                    ),
                ),
                (
                    "total_return",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Retorno Total",
                    ),
                ),
                (
                    "sma_5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="SMA 5",
                    ),
                ),
                (
                    "sma_10",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="SMA 10",
                    ),
                ),
                (
                    "sma_20",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="SMA 20",
                    ),
                ),
                (
                    "sma_50",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="SMA 50",
                    ),
                ),
                (
                    "sma_100",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="SMA 100",
                    ),
                ),
                (
                    "sma_200",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="SMA 200",
                    ),
                ),
                (
                    "ema_5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="EMA 5",
                    ),
                ),
                (
                    "ema_10",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="EMA 10",
                    ),
                ),
                (
                    "ema_20",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="EMA 20",
                    ),
                ),
                (
                    "ema_50",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="EMA 50",
                    ),
                ),
                (
                    "ema_100",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="EMA 100",
                    ),
                ),
                (
                    "ema_200",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="EMA 200",
                    ),
                ),
                (
                    "volatility_5d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Volatilidade 5d",
                    ),
                ),
                (
                    "volatility_10d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Volatilidade 10d",
                    ),
                ),
                (
                    "volatility_20d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Volatilidade 20d",
                    ),
                ),
                (
                    "volatility_30d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Volatilidade 30d",
                    ),
                ),
                (
                    "atr_14",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="ATR 14",
                    ),
                ),
                (
                    "bb_upper",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="BB Superior",
                    ),
                ),
                (
                    "bb_middle",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="BB Média",
                    ),
                ),
                (
                    "bb_lower",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="BB Inferior",
                    ),
                ),
                (
                    "bb_width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="BB Largura",
                    ),
                ),
                (
                    "bb_position",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="BB Posição",
                    ),
                ),
                (
                    "rsi_14",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="RSI 14",
                    ),
                ),
                (
                    "rsi_21",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="RSI 21",
                    ),
                ),
                (
                    "macd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="MACD",
                    ),
                ),
                (
                    "macd_signal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="MACD Sinal",
                    ),
                ),
                (
                    "macd_histogram",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="MACD Histograma",
                    ),
                ),
                (
                    "stoch_k",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Estocástico K",
                    ),
                ),
                (
                    "stoch_d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Estocástico D",
                    ),
                ),
                (
                    "williams_r",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Williams %R",
                    ),
                ),
                (
                    "volume_sma_20",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Volume SMA 20"
                    ),
                ),
                (
                    "volume_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Razão Volume",
                    ),
                ),
                (
                    "obv",
                    models.BigIntegerField(blank=True, null=True, verbose_name="OBV"),
                ),
                (
                    "vpt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=20,
                        null=True,
                        verbose_name="VPT",
                    ),
                ),
                (
                    "mfi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="MFI",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "stock_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="stocks.stockdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador Técnico",
                "verbose_name_plural": "Indicadores Técnicos",
                "db_table": "technical_indicators",
                "ordering": ["-datetime", "ticker"],
            },
        ),
        migrations.AddIndex(
            model_name="stockdata",
            index=models.Index(
                fields=["datetime"], name="stock_data_datetim_27efa3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockdata",
            index=models.Index(fields=["ticker"], name="stock_data_ticker_8272b1_idx"),
        ),
        migrations.AddIndex(
            model_name="stockdata",
            index=models.Index(
                fields=["datetime", "ticker"], name="stock_data_datetim_02c229_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockdata",
            unique_together={("datetime", "ticker")},
        ),
        migrations.AddIndex(
            model_name="technicalindicators",
            index=models.Index(
                fields=["datetime"], name="technical_i_datetim_b1020a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="technicalindicators",
            index=models.Index(fields=["ticker"], name="technical_i_ticker_6d1cb3_idx"),
        ),
        migrations.AddIndex(
            model_name="technicalindicators",
            index=models.Index(
                fields=["datetime", "ticker"], name="technical_i_datetim_e9611f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="technicalindicators",
            unique_together={("datetime", "ticker")},
        ),
    ]
